---
name: Install Bicep and Update AZ PowerShell
description: Install Bicep, Add to the Path and Update Az PowerShell to latest version

runs:
  using: "composite"
  steps:
    - name: Add Az Module to Runner
      run: |
        if(!(Test-Path -Path "/usr/share/az_12.5.0")) {
          mkdir "/usr/share/az_12.5.0"
          Save-Module -Name AZ -RequiredVersion 12.5.0 -path "/usr/share/az_12.5.0"
        }
      shell: pwsh

    - name: Install Bicep
      run: |
        $TOOLS_PATH = "$($env:GITHUB_WORKSPACE)/tools"
        $installDir = Join-Path -Path $TOOLS_PATH -ChildPath "bicep"

        $toolFileName = "bicep"
        $toolFilePath = Join-Path -Path $installDir -ChildPath $toolFileName

        if(!(Test-Path $installDir)) {
          New-Item -ItemType Directory -Path $installDir | Out-String | Write-Verbose
        }

        $url = "https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64"

        Invoke-WebRequest -Uri $url -OutFile "$toolFilePath" | Out-String | Write-Verbose

        $isExecutable = $(test -x $toolFilePath; 0 -eq $LASTEXITCODE)
        if(!($isExecutable)) {
          chmod +x $toolFilePath
        }

        $env:PATH = "$($installDir):$env:PATH"
        echo "$installDir" >> $env:GITHUB_PATH

        bicep --version

        Write-Host "Installed Latest Bicep Version"
      shell: pwsh
